"""slopguard CLI: scan paths, run as an agent hook, install hooks."""
import argparse
import contextlib
import glob as globlib
import io
import json
import os
import re
import stat
import sys
import tempfile
import tokenize

from . import __version__
from .contracts import check_contracts, schema_messages
from .duplicates import (find_diverged_duplicates, find_duplicate_blocks,
                         find_duplicate_functions)
from .findings import add_fingerprints, at_or_above, counts, sort_findings
from .generic import HASH_COMMENT_EXTS, JS_EXTS, _split_comment, check_generic
from .pychecks import check_python
from .testchecks import check_generic_tests, check_python_tests

PY_EXT = ".py"
SUPPORTED_EXTS = {
    ".py", ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".go", ".rs",
    ".java", ".kt", ".swift", ".cs", ".rb", ".php", ".c", ".cc", ".cpp",
    ".h", ".hpp", ".scala", ".sh",
}
IGNORED_DIR_PARTS = {
    "node_modules", ".git", ".hg", ".venv", "venv", "env", "dist", "build",
    "target", "vendor", "__pycache__", ".next", ".tox", "site-packages",
    ".cache", "coverage",
}
GENERATED_SUFFIXES = (".min.js", ".min.css", "_pb2.py", "_pb2_grpc.py", ".d.ts")
_GENERATED_MARKER = re.compile(
    rb"@generated|do not edit|auto-?generated|code generated by", re.I)
_GENERATED_HEAD_BYTES = 400
SCHEMA_EXTS = {
    ".proto", ".textproto", ".avsc", ".thrift", ".graphql", ".graphqls", ".gql",
}
# JSON/YAML are schemas only when named like one; anything else is data.
_SCHEMA_NAMED = re.compile(r"schema|openapi|swagger|asyncapi", re.I)
_SCHEMA_DATA_EXTS = {".json", ".yaml", ".yml"}
MAX_SCHEMA_FILES = 200
MAX_FILE_BYTES = 512 * 1024
MAX_SCAN_FILES = 4000
TEST_RELAXED_RULES = {"as-any", "ts-ignore", "duplicate-code", "debug-artifact",
                      "long-function", "deep-nesting", "diverged-duplicate",
                      "hand-rolled-contract", "contract-drift-key",
                      "placeholder-body", "write-only-attr", "hedging-comment"}
_TEST_PATH_PARTS = ("/tests/", "/test/", "/__tests__/", "/spec/")
# Pedagogical / intentionally-parallel code: tutorial sources, example apps,
# per-language locale files, benchmark bodies. `/docs/` is deliberately not
# blanket-relaxed: some repositories ship their product from that directory.
_PEDAGOGICAL_PATH_PARTS = ("/docs_src/", "/examples/", "/example/",
                           "/locales/", "/locale/", "/benchmarks/", "/bench/")
_PEDAGOGICAL_BLOCKING_RULES = {"syntax-error", "dead-code"}


def is_pedagogical_path(path, cfg=None):
    """Config can extend (`relaxed_paths`) or replace (`relaxed_paths_only`)
    the default list, so the demotion policy is per-repo, not hardcoded."""
    parts = _PEDAGOGICAL_PATH_PARTS
    if cfg:
        extra = cfg.get("relaxed_paths", [])
        if isinstance(extra, str):
            extra = [extra]
        only = cfg.get("relaxed_paths_only")
        if isinstance(only, list):
            parts = tuple(only)
        elif isinstance(extra, (list, tuple)):
            parts = parts + tuple(extra)
    norm = path.replace(os.sep, "/")
    return any(part in norm for part in parts)


def is_test_file(path):
    base = os.path.basename(path)
    norm = path.replace(os.sep, "/")
    return (".test." in base or ".spec." in base or base.startswith("test_")
            or base.endswith(("_test.py", "_test.go", "_test.ts", "_spec.rb"))
            or any(part in norm for part in _TEST_PATH_PARTS))

RULES = {
    "duplicate-function": "error  py       structurally identical function already exists (names normalized)",
    "dead-code":          "error  py       unreachable statements after return/raise/break/continue",
    "syntax-error":       "error  py       file does not parse",
    "diverged-duplicate": "warn   py       function ~60-97% identical to another — a fork drifting apart",
    "duplicate-code":     "warn   all      copy-pasted block (~6+ normalized lines) appears elsewhere",
    "unused-private":     "warn   py,ts,…  private function/method/field never referenced in its file",
    "write-only-attr":    "warn   py       self._attr assigned but never read",
    "unused-import":      "warn   py       import never used",
    "placeholder-body":   "warn   py       function body is pass/... — looks implemented, does nothing",
    "swallowed-exception":"warn   py,js,…  except:pass / empty catch block",
    "bare-except":        "warn   py       bare `except:`",
    "mutable-default":    "warn   py       mutable default argument",
    "hedging-comment":    "warn   all      \"in a real implementation...\"-style cop-out comments",
    "redundant-comment":  "warn   all      comment restates the code (warn if fully, info if mostly)",
    "long-function":      "warn   py       function longer than max_function_lines (default 80)",
    "deep-nesting":       "warn   py       nesting deeper than max_nesting (default 4)",
    "as-any":             "warn   ts       `as any` cast",
    "ts-ignore":          "warn   ts       @ts-ignore / @ts-nocheck",
    "contract-drift-key": "warn   py       camelCase key with no schema field, in a dict that speaks the schema",
    "hand-rolled-contract":"warn  py       dict literal hand-builds a schema-defined message",
    "contract-case-skew": "info   py       in-sync hand-mapping of a schema field (parentFrame for parent_frame)",
    "no-assert-test":     "warn   tests    test never asserts — only proves the code doesn't crash",
    "mock-only-test":     "info   tests    every assertion is a mock-call assertion — 0% precision on driver-style tests, demoted pending better discrimination",
    "mock-echo-test":     "warn   tests    asserts the exact value the mock was told to return",
    "tautological-assert":"warn   tests    assert True / expect(x).toBe(x) — always passes",
    "conditional-assert": "warn   tests    assertion inside an `if` — only checks on some paths",
    "brittle-exact-string":"warn  tests    equality against a long literal string",
    "overspecified-assert":"warn  tests    equality against a big literal dict/list — pins every field",
    "parametrize-candidate":"warn tests    3+ tests identical except literals — collapse to one parametrized test",
    "private-poke-test":  "warn   tests    test reads `_private` internals instead of the public API",
    "excessive-mocking":  "warn   tests    6+ mocks in one test — tests the wiring diagram",
    "sleep-in-test":      "warn   tests    real sleep/setTimeout wait — slow and flaky",
    "type-ignore":        "info   py       `# type: ignore`",
    "single-method-class":"info   py       class wrapping a single method",
    "debug-artifact":     "info   py,js    print()/console.log leftovers",
}


def load_config(start_dir):
    cfg = {}
    d = os.path.abspath(start_dir)
    while True:
        candidate = os.path.join(d, ".slopguard.json")
        if os.path.isfile(candidate):
            try:
                with open(candidate) as fh:
                    cfg = json.load(fh)
            except (OSError, ValueError):
                cfg = {}
            if not isinstance(cfg, dict):
                cfg = {}
            cfg["_config_dir"] = d
            break
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    env_disable = os.environ.get("SLOPGUARD_DISABLE_RULES", "")
    if env_disable:
        cfg.setdefault("disable", [])
        cfg["disable"] = list(cfg["disable"]) + [r.strip() for r in env_disable.split(",") if r.strip()]
    return cfg


def is_checkable(path):
    parts = set(os.path.normpath(path).split(os.sep))
    if parts & IGNORED_DIR_PARTS:
        return False
    base = os.path.basename(path)
    if base.endswith(GENERATED_SUFFIXES) or ".gen." in base:
        return False
    if "generated" in os.path.normpath(path).split(os.sep):
        return False
    ext = os.path.splitext(base)[1].lower()
    if ext not in SUPPORTED_EXTS:
        return False
    try:
        if os.path.getsize(path) > MAX_FILE_BYTES:
            return False
        # Machine-written files aren't slop anyone can fix — honor the
        # conventional header markers (@generated / DO NOT EDIT / ...).
        with open(path, "rb") as fh:
            if _GENERATED_MARKER.search(fh.read(_GENERATED_HEAD_BYTES)):
                return False
    except OSError:
        return False
    return True


def _walk_checkable(directory):
    for root, dirs, names in os.walk(directory):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIR_PARTS and not d.startswith(".")]
        for name in sorted(names):
            fp = os.path.join(root, name)
            if is_checkable(fp):
                yield fp


def collect_files(paths):
    files = []
    for p in paths:
        p = os.path.abspath(p)
        if os.path.isfile(p) and is_checkable(p):
            files.append(p)
        elif os.path.isdir(p):
            files.extend(_walk_checkable(p))
    return files


def is_schema_file(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in SCHEMA_EXTS:
        return True
    return ext in _SCHEMA_DATA_EXTS and bool(_SCHEMA_NAMED.search(os.path.basename(path)))


def _walk_schemas(directory, dir_budget):
    for root, dirs, names in os.walk(directory):
        if dir_budget is not None:
            if not dir_budget[0]:
                return
            dir_budget[0] -= 1
        dirs[:] = sorted(
            d for d in dirs
            if d not in IGNORED_DIR_PARTS and not d.startswith("."))
        for name in sorted(names):
            if is_schema_file(name):
                yield os.path.join(root, name)


def collect_schema_files(paths, max_files=MAX_SCHEMA_FILES, max_dirs=None):
    """Message-schema files under the given paths (see is_schema_file)."""
    schemas = []
    dir_budget = [max_dirs] if max_dirs is not None else None
    for p in paths:
        p = os.path.abspath(p)
        if os.path.isfile(p) and is_schema_file(p):
            schemas.append(p)
        elif os.path.isdir(p):
            for schema in _walk_schemas(p, dir_budget):
                schemas.append(schema)
                if len(schemas) >= max_files:
                    return schemas
        if len(schemas) >= max_files:
            return schemas
    return schemas


def read_texts(files):
    texts = {}
    for f in files:
        try:
            with open(f, encoding="utf-8", errors="replace") as fh:
                texts[f] = fh.read()
        except OSError:
            continue
    return texts


def config_schema_files(cfg, max_files=MAX_SCHEMA_FILES, max_dirs=None):
    """Schema files named by config: contract_schemas globs + schema_roots dirs,
    resolved relative to the directory holding .slopguard.json."""
    if max_files <= 0:
        return []
    base = cfg.get("_config_dir") or "."
    files = []
    seen = set()

    def add(path):
        path = os.path.abspath(path)
        if path not in seen and os.path.isfile(path):
            seen.add(path)
            files.append(path)

    patterns = cfg.get("contract_schemas", [])
    if isinstance(patterns, str):
        patterns = [patterns]
    for pattern in patterns if isinstance(patterns, (list, tuple)) else []:
        if not isinstance(pattern, str):
            continue
        resolved = pattern if os.path.isabs(pattern) else os.path.join(base, pattern)
        for match in globlib.iglob(resolved, recursive=True):
            add(match)
            if len(files) >= max_files:
                return files
    roots = cfg.get("schema_roots", [])
    if isinstance(roots, str):
        roots = [roots]
    if isinstance(roots, (list, tuple)):
        dirs = [
            r if os.path.isabs(r) else os.path.join(base, r)
            for r in roots if isinstance(r, str)
        ]
        remaining = max_files - len(files)
        if remaining:
            for path in collect_schema_files(
                    dirs, max_files=remaining, max_dirs=max_dirs):
                add(path)
                if len(files) >= max_files:
                    break
    return files


def _file_findings(item):
    """Per-file rule passes; module-level so multiprocessing can pickle it."""
    path, text, cfg, messages = item
    findings = []
    ext = os.path.splitext(path)[1].lower()
    if ext == PY_EXT:
        findings.extend(check_python(path, text, cfg))
    else:
        findings.extend(check_generic(path, text, cfg, ext))
    if messages:
        findings.extend(check_contracts(path, text, cfg, messages))
    if is_test_file(path):
        if ext == PY_EXT:
            findings.extend(check_python_tests(path, text, cfg))
        elif ext in JS_EXTS:
            findings.extend(check_generic_tests(path, text, cfg, ext))
    return findings


PARALLEL_MIN_FILES = 200  # process pool amortizes only on sizable scans


def analyze(texts, cfg, report_files=None, schema_texts=None, parallel=False,
            fingerprint_root=None, function_duplicates=True):
    """texts: {path: content}. report_files limits which files findings are
    reported FOR; all files still provide duplicate-detection context.
    schema_texts: {path: content} of schema files defining the repo's message
    contracts (kept out of texts so they aren't scanned as code).
    function_duplicates=False retains only the cheap line-clone pass."""
    findings = []
    messages = schema_messages(schema_texts) if schema_texts else []
    items = [(path, text, cfg, messages) for path, text in texts.items()
             if report_files is None or path in report_files]
    if parallel and len(items) >= PARALLEL_MIN_FILES:
        import multiprocessing
        with multiprocessing.Pool() as pool:
            for batch in pool.imap_unordered(_file_findings, items, chunksize=16):
                findings.extend(batch)
    else:
        for item in items:
            findings.extend(_file_findings(item))

    findings.extend(find_duplicate_blocks(texts))
    if function_duplicates:
        py_texts = {p: t for p, t in texts.items() if p.endswith(PY_EXT)}
        findings.extend(find_duplicate_functions(
            py_texts, report_files=report_files))
        findings.extend(find_diverged_duplicates(
            py_texts, report_files=report_files))

    if report_files is not None:
        findings = [f for f in findings if f.file in report_files]

    # Patterns that are conventional in tests (mock casts, repeated setup
    # blocks) drop to info there instead of blocking; structural heuristics in
    # pedagogical paths (tutorial sources, locales, benchmarks) do likewise.
    for f in findings:
        if f.severity == "warn" and f.rule in TEST_RELAXED_RULES and is_test_file(f.file):
            f.severity = "info"
        if f.severity in ("warn", "error") and is_pedagogical_path(f.file, cfg) \
                and f.rule not in _PEDAGOGICAL_BLOCKING_RULES:
            f.severity = "info"

    disabled = set(cfg.get("disable", []))
    findings = [f for f in findings if f.rule not in disabled]
    findings = sort_findings(suppress_ignored(findings, texts))
    root = fingerprint_root or cfg.get("_config_dir") or os.getcwd()
    return add_fingerprints(findings, texts, root)


BASELINE_NAME = ".slopguard-baseline.json"


def project_root(start_dir, cfg=None):
    """Stable root for fingerprints and a new baseline.

    Prefer explicit project markers over the scanned subdirectory. For
    configless, non-git trees invoked through a relative path, the caller's
    working directory is the least surprising project root."""
    relative_start = not os.path.isabs(start_dir)
    if cfg and cfg.get("_config_dir"):
        return os.path.abspath(cfg["_config_dir"])
    d = os.path.abspath(start_dir)
    if os.path.isfile(d):
        d = os.path.dirname(d)
    probe = d
    while True:
        if os.path.exists(os.path.join(probe, ".git")):
            return probe
        parent = os.path.dirname(probe)
        if parent == probe:
            break
        probe = parent
    if relative_start:
        cwd = os.path.abspath(os.getcwd())
        with contextlib.suppress(ValueError):
            if os.path.commonpath((cwd, d)) == cwd:
                return cwd
    return d


def find_baseline(start_dir):
    """Walk up from start_dir; returns (baseline_path, fingerprint_mapping)
    or (None, {}). The baseline file's directory is the fingerprint root."""
    d = os.path.abspath(start_dir)
    while True:
        candidate = os.path.join(d, BASELINE_NAME)
        if os.path.isfile(candidate):
            try:
                with open(candidate) as fh:
                    data = json.load(fh)
                entries = data.get("fingerprints", {})
                if not isinstance(data, dict) or not isinstance(entries, dict):
                    return candidate, {}
                entries = {
                    fp: entry for fp, entry in entries.items()
                    if isinstance(fp, str) and isinstance(entry, dict)
                    and isinstance(entry.get("file"), str)
                }
                return candidate, entries
            except (AttributeError, OSError, TypeError, ValueError):
                return candidate, {}
        parent = os.path.dirname(d)
        if parent == d:
            return None, {}
        d = parent


def apply_baseline(findings, baseline_fps):
    """Ratchet: drop findings already in the baseline; new ones stay hot."""
    if not baseline_fps:
        return findings, 0
    kept = [f for f in findings if f.fingerprint not in baseline_fps]
    return kept, len(findings) - len(kept)


def write_baseline(path, findings, preserved=None):
    entries = dict(preserved or {})
    entries.update({
        f.fingerprint: {"rule": f.rule, "file": os.path.relpath(f.file, os.path.dirname(path)),
                        "line": f.line}
        for f in at_or_above(findings, "warn")
    })
    content = json.dumps(
        {"version": 1, "fingerprints": entries}, indent=1, sort_keys=True) + "\n"
    directory = os.path.dirname(path) or "."
    try:
        mode = stat.S_IMODE(os.stat(path).st_mode)
    except FileNotFoundError:
        mode = None
    fd, tmp = tempfile.mkstemp(prefix=".slopguard-baseline-", dir=directory)
    try:
        with os.fdopen(fd, "w") as fh:
            fd = None
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        if mode is not None:
            os.chmod(tmp, mode)
        os.replace(tmp, path)
    except Exception:
        if fd is not None:
            with contextlib.suppress(OSError):
                os.close(fd)
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise
    return len(entries)


def _baseline_entry_in_scope(entry, baseline_path, paths):
    """Whether a stored finding belongs to the paths being ratcheted."""
    rel = entry.get("file")
    if not isinstance(rel, str):
        return False
    target = os.path.abspath(os.path.join(os.path.dirname(baseline_path), rel))
    for raw in paths or ["."]:
        scope = os.path.abspath(raw)
        if os.path.isdir(scope):
            try:
                if os.path.commonpath((scope, target)) == scope:
                    return True
            except ValueError:
                continue
        elif target == scope:
            return True
    return False


def suppress_ignored(findings, texts):
    """Drop findings suppressed by a slopguard:ignore comment on (or directly
    above) their line. `slopguard:ignore rule-name` suppresses only that rule;
    a bare `slopguard:ignore` suppresses everything on the line."""
    kept = []
    ignore_cache = {}
    for f in findings:
        if f.file not in ignore_cache:
            ignore_cache[f.file] = _ignore_lines(f.file, texts.get(f.file, ""))
        if not _is_suppressed(f, ignore_cache[f.file]):
            kept.append(f)
    return kept


def _is_suppressed(finding, ignored):
    for lineno in (finding.line, finding.line - 1):
        scope = ignored.get(lineno, False)
        if scope is False:
            continue
        if scope is None or finding.rule in scope:
            return True
    return False


def _ignore_scope(comment):
    """None = suppress all rules; a set = suppress only those named.

    Rule names must appear between `slopguard:ignore` and any dash-separated
    reason ("slopguard:ignore swallowed-exception — expected on cancel")."""
    _, _, rest = comment.partition("slopguard:ignore")
    rest = re.split(r"—|--|\(", rest, maxsplit=1)[0]
    named = {tok for tok in re.findall(r"[a-z][a-z-]*[a-z]", rest) if tok in RULES}
    return named or None


def _ignore_lines(path, text):
    """{lineno: scope} for slopguard:ignore comments (see _ignore_scope)."""
    if path.lower().endswith(PY_EXT):
        try:
            tokens = tokenize.generate_tokens(io.StringIO(text).readline)
            return {
                tok.start[0]: _ignore_scope(tok.string)
                for tok in tokens
                if tok.type == tokenize.COMMENT and "slopguard:ignore" in tok.string
            }
        except (tokenize.TokenError, IndentationError, SyntaxError):
            return {
                lineno: _ignore_scope(line)
                for lineno, line in enumerate(text.splitlines(), 1)
                if "slopguard:ignore" in line
            }

    ext = os.path.splitext(path)[1].lower()
    marker = "#" if ext in HASH_COMMENT_EXTS else "//"
    ignored = {}
    for lineno, line in enumerate(text.splitlines(), 1):
        _, comment = _split_comment(line, marker)
        if comment is not None and "slopguard:ignore" in comment:
            ignored[lineno] = _ignore_scope(comment)
    return ignored


def print_report(findings, out=sys.stdout):
    for f in sort_findings(findings):
        out.write(f.format() + "\n")
    c = counts(findings)
    out.write("\n%d finding(s): %d error, %d warn, %d info\n"
              % (len(findings), c["error"], c["warn"], c["info"]))


def _scan_findings(args):
    """Shared analysis for scan/baseline: (findings, cfg, baseline_path)."""
    start = args.paths[0] if args.paths else "."
    cfg = load_config(start)
    for rule in getattr(args, "disable", None) or []:
        cfg.setdefault("disable", []).append(rule)
    files = collect_files(args.paths or ["."])
    if not files:
        return None, cfg, None
    truncated = len(files) > MAX_SCAN_FILES
    if truncated:
        print("slopguard: %d checkable files found — scanning only the first %d. "
              "Point slopguard at a narrower path for full coverage."
              % (len(files), MAX_SCAN_FILES), file=sys.stderr)
        files = files[:MAX_SCAN_FILES]
    texts = read_texts(files)
    schema_paths = [p if os.path.isdir(p) else os.path.dirname(os.path.abspath(p)) or "."
                    for p in (args.paths or ["."])]
    schema_files = config_schema_files(cfg)
    remaining = MAX_SCHEMA_FILES - len(schema_files)
    if remaining:
        schema_files.extend(collect_schema_files(schema_paths, max_files=remaining))
    schema_texts = read_texts(sorted(set(schema_files)))

    start_dir = start if os.path.isdir(start) else os.path.dirname(start) or "."
    baseline_path, baseline_entries = find_baseline(start_dir)
    root = (os.path.dirname(baseline_path) if baseline_path
            else project_root(start_dir, cfg))
    findings = analyze(texts, cfg, schema_texts=schema_texts, parallel=True,
                       fingerprint_root=root)
    return ((findings, baseline_entries, truncated), cfg,
            baseline_path or os.path.join(root, BASELINE_NAME))


def cmd_scan(args):
    result, cfg, _ = _scan_findings(args)
    if result is None:
        print("slopguard: no checkable files found", file=sys.stderr)
        return 0
    findings, baseline_fps, _truncated = result
    if args.no_baseline:
        baseline_fps = set()
    findings, hidden = apply_baseline(findings, baseline_fps)
    if args.json:
        print(json.dumps([f.to_dict() for f in sort_findings(findings)], indent=2))
    else:
        print_report(findings)
        if hidden:
            print("(%d baselined finding(s) hidden — `slopguard scan --no-baseline` shows them)"
                  % hidden)
    fail_on = args.fail_on or cfg.get("fail_on", "warn")
    if fail_on != "never" and at_or_above(findings, fail_on):
        return 1
    return 0


def cmd_baseline(args):
    result, _cfg, baseline_path = _scan_findings(args)
    if result is None:
        print("slopguard: no checkable files found", file=sys.stderr)
        return 1
    findings, existing, truncated = result
    if truncated:
        print("slopguard: refusing to write a baseline from a truncated scan; "
              "use narrower paths", file=sys.stderr)
        return 1
    if args.update:
        current = {f.fingerprint for f in at_or_above(findings, "warn")}
        findings = [
            f for f in findings
            if f.fingerprint in (set(existing) & current)
        ]
        preserved = {
            fp: entry for fp, entry in existing.items()
            if not _baseline_entry_in_scope(entry, baseline_path, args.paths)
        }
        n = write_baseline(baseline_path, findings, preserved)
        print("baseline updated: %d fingerprint(s) remain (fixed findings removed, "
              "new ones stay hot) — %s" % (n, baseline_path))
    else:
        n = write_baseline(baseline_path, findings)
        print("baseline written: %d warn+ finding(s) grandfathered — %s"
              % (n, baseline_path))
        print("new findings will still block; shrink the file with `slopguard baseline --update`")
    return 0


def cmd_rules(_args):
    for rule, desc in RULES.items():
        print("%-22s %s" % (rule, desc))
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="slopguard",
        description="Static checks for the failure modes of AI-generated code.")
    parser.add_argument("--version", action="version", version="slopguard %s" % __version__)
    sub = parser.add_subparsers(dest="command")

    p_scan = sub.add_parser("scan", help="scan files/directories")
    p_scan.add_argument("paths", nargs="*", default=["."])
    p_scan.add_argument("--json", action="store_true")
    p_scan.add_argument("--fail-on", choices=["error", "warn", "never"])
    p_scan.add_argument("--disable", action="append", metavar="RULE")
    p_scan.add_argument("--no-baseline", action="store_true",
                        help="report baselined (grandfathered) findings too")
    p_scan.set_defaults(func=cmd_scan)

    p_base = sub.add_parser(
        "baseline",
        help="grandfather current warn+ findings so only NEW ones block (ratchet)")
    p_base.add_argument("paths", nargs="*", default=["."])
    p_base.add_argument("--update", action="store_true",
                        help="shrink the baseline: drop fingerprints for findings now fixed")
    p_base.set_defaults(func=cmd_baseline)

    p_hook = sub.add_parser("hook", help="run as a Claude Code / Codex hook (JSON on stdin)")
    p_hook.add_argument("--agent", choices=["claude", "codex"], default="claude")
    p_hook.set_defaults(func=None)  # resolved lazily to keep hook startup light

    p_inst = sub.add_parser("install", help="wire the hook into an agent's config")
    p_inst.add_argument("agent", choices=["claude", "codex"])
    p_inst.set_defaults(func=None)

    p_rules = sub.add_parser("rules", help="list rules")
    p_rules.set_defaults(func=cmd_rules)

    args = parser.parse_args(argv)
    if args.command == "hook":
        from .hook import run_hook
        return run_hook(args)
    if args.command == "install":
        from .install import run_install
        return run_install(args)
    if not args.command:
        parser.print_help()
        return 0
    return args.func(args)
